global:
  input_base: "<Paired End input files>"
  output_base: "<output dir>"
  script_path: "main.py"

tools:
  trimmomatic:
    adapter_file: all_adapters.fa
    threads: NN
    other_params: "LEADING:14 TRAILING:0 SLIDINGWINDOW:4:20 MINLEN:40"

  sortmerna:
    db_dir: SILVA_138.2_combined_SSU_LSU_NR99.fasta
    threads: NN

  fastqc:
    threads: NN

  diamond:
    db: diamondDB.dmnd
    threads: NN
    evalue: 1e-5
    max_targets: X

  multiqc:
    output_dir: "<output dir>"

taxonomy:
  sqlite_db: "prot_accession2taxid.db"
  nodes_dmp: "nodes.dmp"
  names_dmp: "names.dmp"

params:
  merge_tool: PEAR
  keep_intermediate: true
  log_level: INFO

